version: "3.9"
services:

  spring:
    container_name: matager_backend
    build: .
    ports:
      - "5009:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:mysql://matager_backend_mysql:3306/matager?creatDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: matagerSecret2024@GOOD
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: matager_backend_mysql
    image: mysql:8
    ports:
      - "3009:3306"
    volumes:
      - /home/ubuntu/matager_backend/mysql-docker-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: matager
      MYSQL_ROOT_PASSWORD: matagerSecret2024@GOOD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3